### ISSUE TITLE
(cl-no-applicable-method project-root (vc . "/X/Y/Z")) with emacs 26.3

### ISSUE THREAD

**Issue by adl** [emacs-ess/ESS#1052]
Hi

My automated builds, which include some R snippets executed by org-babel via ESS, are suddenly getting a lot of failures with the following backlog:

```
Debugger entered--Lisp error: (cl-no-applicable-method project-root (vc . "/builds/spot/spot/"))
  signal(cl-no-applicable-method (project-root (vc . "/builds/spot/spot/")))
  cl-no-applicable-method(#s(cl--generic :name project-root :dispatches ((0 #s(cl--generic-generalizer :name cl--generic-head-generalizer :priority 80 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x199a21>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x199a41>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x198afd>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x198b11>)))) :method-table (#s(cl--generic-method :specializers ((head ess-r-package)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) "Return the project root for ESS R packages" #<bytecode 0xf2f4d9>))) :options nil) (vc . "/builds/spot/spot/"))
  apply(cl-no-applicable-method #s(cl--generic :name project-root :dispatches ((0 #s(cl--generic-generalizer :name cl--generic-head-generalizer :priority 80 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x199a21>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x199a41>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x198afd>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x198b11>)))) :method-table (#s(cl--generic-method :specializers ((head ess-r-package)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) "Return the project root for ESS R packages" #<bytecode 0xf2f4d9>))) :options nil) (vc . "/builds/spot/spot/"))
  #f(compiled-function (&rest args) #<bytecode 0x16644f5>)((vc . "/builds/spot/spot/"))
  apply(#f(compiled-function (&rest args) #<bytecode 0x16644f5>) (vc . "/builds/spot/spot/") nil)
  ess-project-root((vc . "/builds/spot/spot/"))
  ess-gen-proc-buffer-name:project-or-simple("R")
  inferior-ess--get-proc-buffer-create("R")
[...]
```

The above is with vanilla Emacs 26.3 plus ess-20201004.1522 freshly installed from Melpa in a docker image.

My belief is that this is coming from commit a694b2627992bda5489c1b4b5bb750c590aa8d85.  The following definition of `ess-project-root`:
```lisp
(defalias 'ess-project-root
    ;; TODO: Remove once we drop support for Emacs 27
    (if (fboundp 'project-root)
        'project-root
      (lambda (project)
        (car (project-roots project)))))
```
always seems to resolve to `'project-root`, because even if Emacs 26.3 does not define that symbol in `project.el`, this very patch defines it in `ess-r-package.el`.

**Comment by jabranham** [comment]
Hm... yes, true. ess-utils gets compiled for me before ess-r-package so it's not an issue but we shouldn't depend on that.

I was hoping `cl-generic-p` would solve the issue but that doesn't seem to help.

**Comment by adl** [comment]
It might also be possible that another package defines the `project-root` method for compatibility with future versions of `project.el`.

How about using

```elisp
   (if (get 'project-roots 'byte-obsolete-info)
       'project-root
     (lambda ...))
```
Rational: when `project-root` [was introduced](https://github.com/emacs-mirror/emacs/commit/5044c19001fe608f2eac621add2e05cbca6c804b), `project-roots` was marked as obsolete.

-----


For anyone else facing a similar issue my current workaround is simply:
```
(setq ess-gen-proc-buffer-name-function 'ess-gen-proc-buffer-name:directory)
(setq ess-use-flymake nil)
```
(Note that I'm only using ESS through org-mode and in batch mode, so I do not really mind those features.)

**Comment by jabranham** [comment]
Thanks! I've pushed b8a097d362e85ec499ee4c1265046530bd402c24 which I'm hoping fixes this issue, let me know if it pops up again for you.

Travis was being unhelpful so hopefully this doesn't break anything :-)

**Comment by mrepetto94** [comment]
I still have that problem even with the:
'''
(setq ess-gen-proc-buffer-name-function 'ess-gen-proc-buffer-name:directory)
(setq ess-use-flymake nil)
'''

Outside a project 'ess-run-r' works fine

**Comment by PhilippRonchen** [comment]
I have a similar problem on Emacs 27.1 (within Spacemacs). When I run any command in ess-mode within a projectile, I get the error:
`No applicable method project-roots, (projectile [projectile location])`

Outside a projectile everything works fine. I tried adding the code 
```
(setq ess-gen-proc-buffer-name-function 'ess-gen-proc-buffer-name:directory)
(setq ess-use-flymake nil)
```

to my dot-file as well as adding the code snippets suggested in the related issue [https://github.com/emacs-lsp/lsp-mode/issues/2335](url), but none of this resolved the issue. I would appreciate any suggestions on what a workaround might be.
