### ISSUE TITLE
(load 'ess-site "path/to/ess/lisp")   no longer correctly starts ESS

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#411]
Maybe that is intended by the "cleanup".
But it breaks ~20 years of history on how ESS should be initialized.... and hence my private configuration of emacs startup and ESS initialization.

The error is that  it does not find 'ess-utils ... and the reason is that loading ess-site does no longer ensure ESS is on the emacs `load-path.

**Comment by mmaechler** [comment]
Well, we had a chicken and egg problem in `ess-site.el`:  It load `ess-utils` before setting the `load-path`  but the `ess-lisp-directory` was in `ess-utils` and that was needed to set the `load-path`.

The solutiion was to bring `ess-lisp-directory` back to `ess-site.el`.

**Comment by slyrus** [comment]
I can't build with this change. I get the following error:

make[1]: Entering directory '/home/sly/.emacs.d/site-lisp/ESS/lisp'
emacs -batch -no-site-file -no-init-file -l ./ess-comp.el -f batch-byte-compile ess-custom.el
loading ’ess-compat ..
loading ’ess-custom ..
loading ’ess ..
Symbol’s value as variable is void: ess-lisp-directory
Makefile:119: recipe for target 'ess-custom.elc' failed
make[1]: *** [ess-custom.elc] Error 255
make[1]: Leaving directory '/home/sly/.emacs.d/site-lisp/ESS/lisp'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2


Backing up to one commit to 1fde11acc8803298daf08247a861917b3f6ccf34 allows me to build.

**Comment by lionel-** [comment]
@slyrus I've redefined `ess-lisp-directory` in `ess-utils` to fix the build for now. We should get rid of any dependency on that variable because ESS mode internals should be completely agnostic about where they have been built.

**Comment by slyrus** [comment]
Thanks. That seems to have fixed things!

**Comment by mmaechler** [comment]
"Same" problem  as 2 years ago:   I  `(load ".....path_to_ess/lisp/ess-site")`  and that fails since today because  it can't find `ess-utils`  because   `....path-to/ess/lisp`  is not yet in emacs `load-path`.

Solution revert something such that `ess-site` *again* extends emacs' `load-path` ... as it has always done.

**Comment by mmaechler** [comment]
Bug:  My startup of emacs fails early ... and I have to dig a while and have only cumbersome workaround by manually adding  `".../ess/lisp"`  to `load-path`

**Comment by lionel-** [comment]
Note that it's better to reopen a new issue because this one, despite being open again, is burried deep in the issue list as it's so old.

I think that's from https://github.com/emacs-ess/ESS/pull/881

Now that I look at it again, it seems weird to have load-path manipulation in ess-custom. Perhaps best to revert entirely @jabranham? We also need to add a comment that the duplication is necessary because the historical way of loading ESS was through ess-site, but we still need the rest of the package to be independent from ess-site. So we need the logic in two places.

**Comment by mmaechler** [comment]
- reopening a new issue: Yes, I'll do next time... It's a pity open issues are not sorted according to "last activity" 

- yes, I understand it's a bit awkward to keep expand `load-path` in two places.  Maybe we could factor it out into say `ess-load-path.el`  and load that "from this file's directory" in  `ess-site.el` and `ess-*.el` .. 
*iff* there's a good concept  of "this file's directory" we can use.

**Comment by jabranham** [comment]
Another solution is to assume that ESS's elisp files are already on load-path. This is what most (all?) other elisp packages do. 

@lionel- Why do you think it's odd to manipulate load-path in ess-custom?

**Comment by lionel-** [comment]
> Why do you think it's odd to manipulate load-path in ess-custom?

Because it seems `load-path` manipulation should be done in the user configuration or by the package system. `ess-site.el` is a convenience file that is not really part of the ESS codebase so it's a bit less strange. Is it common to manipulate load-path from package code?

> Another solution is to assume that ESS's elisp files are already on load-path.

Will this affect end users other than ourselves?

By the way, if I'm not mistaken this problem should be solved once ESS is distributed in the form of an `M-x package-install`able tarball. We have a working Makefile target for this right? Maybe we should try it for our next release tarball.

**Comment by vspinu** [comment]
I think those fundamental dir vars and path manipulation should be in ess.el and ess.el should be required from ess-site.el. This should solve the issue.

**Comment by jabranham** [comment]
@vspinu It won't. People who `(load ess-site)` without having the load path set up already will still get this (which was the case above, if I recall correctly).

**Comment by vspinu** [comment]
The problem is for those people who do `(load "/full/path/to")` as @mmaechler reported. Of course `(load "ess-site")` would never work without the path.

**Comment by mmaechler** [comment]
> The problem is for those people who do `(load "/full/path/to")` as @mmaechler reported. Of course `(load "ess-site")` would never work without the load-path setup.

Yes, of course... I'm editing the subject to correct this.

**Comment by jabranham** [comment]
@vspinu so it sounds like the current situation is good as far as you're concerned, right? They're currently set in ess-custom, which is required by all ess files (including from ess-site).

IOW can we close this?

**Comment by vspinu** [comment]
@jabranham, no. ess-custom is not required from ess-utils nor from ess-site. 

Let's put them to ess.el where they naturally belong.  I think we should start moving away from this "all-customs-in-one-place" idea anyhow.

**Comment by vspinu** [comment]
It is actually required from ess-utils but that doesn't help becuse emacs fails on the very first `ess-utils` require. So my proposal will not work either. One need to add to load path directly in the `ess-site.el`. No other solution unfortunately.

**Comment by vspinu** [comment]
Ok, I have fixed the load. Not a big deal.

What strikes me as unnatural is that we have our dirs defcustom. That's a bit crazy, one has to load ESS in order to have those defined, so it's a chicken egg problem. Those are variables set automatically or by site-configuration. This is the result of dc8880f32. I would say we make them defvars again and place in ess.el.

**Comment by jabranham** [comment]
> That's a bit crazy, one has to load ESS in order to have those defined,

No, customize sets variables values before packages are loaded.

Also, it would've been nice to at least talk about the change before committing it straight to master. #881 was open for a week before merging.

> I would say we make them defvars again and place in ess.el.

Why ess.el and not ess-mode.el? I thought we were putting things in ess-mode.el, not ess.el, wasn't that the decision we made back in 7df0059d88b55a21698963c14613a772dce8f0e0?

**Comment by lionel-** [comment]
> Also, it would've been nice to at least talk about the change before committing it straight to master. #881 was open for a week before merging.

Agreed that a PR is the correct method of pushing changes for things that are under discussion.
