### ISSUE TITLE
Trouble with viewing `tibble` on Rdired

### ISSUE THREAD

**Issue by shgoke** [emacs-ess/ESS#810]
I have recently migrated from RStudio to ESS, and it's been great --- thanks for developing this! That said, I wish to solve the trouble in viewing [tibbles](https://tibble.tidyverse.org) on Rdired. Let's say I create a simple tibble

    library(tibble)
    df <- tibble(a=1:100, b=301:400)

and view it on Rdired. The result is truncated at 10 observations (just like when I type `df` on the R console) and includes ugly control characters:

    ^[[90m# A tibble: 100 x 2^[[39m
           a     b
       ^[[3m^[[90m<int>^[[39m^[[23m ^[[3m^[[90m<int>^[[39m^[[23m
    ^[[90m 1^[[39m     1   301
    ^[[90m 2^[[39m     2   302
    ^[[90m 3^[[39m     3   303
    ^[[90m 4^[[39m     4   304
    ^[[90m 5^[[39m     5   305
    ^[[90m 6^[[39m     6   306
    ^[[90m 7^[[39m     7   307
    ^[[90m 8^[[39m     8   308
    ^[[90m 9^[[39m     9   309
    ^[[90m10^[[39m    10   310
    ^[[90m# … with 90 more rows^[[39m

My environment: OS X Mojave, Emacs ver. 26.1, installed ESS (ver. 18.10.3) from MELPA using `package.el`.

Using tibbles makes my codes so much readable, and I often want to view tables outside the console. So I'd really appreciate your help.

**Comment by lionel-** [comment]
Looks like the color filter should be applied in Rdired buffers (I had no idea we even have this). In the meantime you can disable r-lib and tidyverse colouring by setting `options(crayon.enabled = FALSE)` in your RProfile.

**Comment by shgoke** [comment]
Thanks, setting `options(crayon.enabled = FALSE)` in `.Rprofile` eliminates the control characters. Meanwhile the result is still truncated with 10 rows:

    # A tibble: 100 x 2
           a     b
       <int> <int>
     1     1   301
     2     2   302
     3     3   303
     4     4   304
     5     5   305
     6     6   306
     7     7   307
     8     8   308
     9     9   309
    10    10   310
    # … with 90 more rows

**Comment by shgoke** [comment]
I have this issue on the Rdired buffer, not on the ESS process buffer (I hope I'm using the terminology correctly). To be more precise, I encounter the problem when I define `df` as above, then run `M-x ess-rdired` and press `v` with the point (cursor) on `df`. The contents of `df` are shown in the buffer `*R view*` with the two problems I mentioned (control characters, truncation of rows).

Yes, I can avoid this problem by disabling coloring and tweaking `tibble.print_max` and `tibble.print_min` in `.Rprofile`, but that also affects outputs when I simply type `df` on the ESS process (or on an R console out of Emacs).

Right now I have a few workaround options (like [using print(n=...) on R console](https://stackoverflow.com/questions/23188900/view-entire-data-frame-when-wrapped-in-tbl-df), or saving the tibble as a `.csv` file and opening it in a spreadsheet software). But an ideal situation for me is to see the tibble with coloring and truncation when I type `df` in the ESS R process / bare R console, but to see the full tibble when I browse it on Rdired - just as I would on RStudio.

**Comment by jabranham** [comment]
Ah, OK. I see. I didn't see this at first because I have `ess-execute-in-process-buffer` set to `t`. I just pushed a commit that should solve this. If you get ESS from MELPA, it should update in the next 8 hours or so.

**Comment by shgoke** [comment]
Thanks for your quick turnaround. The update has eliminated the control characters, but I can still see only 10 rows. The latter issue may be a matter of personal preference (and can be solved by modifying `.Rprofile` if I don't mind that I would also see a long line of tables on the process buffer), but I mention it here just for a record.
